[package]
name = "file_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json", "stream"] }
tokio = { version = "1", features = ["full"] }
structopt = "0.3.13"
indicatif = "0.16.2"
futures-util = "0.3.17"